server:
  port: 8080
spring:
  application:
    name: api-gateway-server
eureka:
  client:
    service-url:
      defaultZone:  http://127.0.0.1:8761/eureka
zuul:
  routes:
    producer:
      path: /product/**
      serviceId:  product-server